version: 2
updates:
    - package-ecosystem: "github-actions"
      directory: "/"
      open-pull-requests-limit: 1
      schedule:
          interval: "weekly"
          day: "monday"
          time: "09:00"
      commit-message:
          prefix: "github actions "
          include: scope
      groups:
          github-dependencies:
              patterns:
                  - "*"

    - package-ecosystem: "pip"
      directories:
          - "/"
          - "/sandbox"
      open-pull-requests-limit: 1
      versioning-strategy: auto
      ignore:
          - dependency-name: "*"
            update-types:
                ["version-update:semver-minor", "version-update:semver-patch"]
      schedule:
          interval: "weekly"
          day: "monday"
          time: "09:00"
      commit-message:
          prefix: "pip "
          include: scope
      groups:
          python-dependencies:
              patterns:
                  - "*"

    - package-ecosystem: "npm"
      directory: "/"
      open-pull-requests-limit: 1
      versioning-strategy: auto
      ignore:
          - dependency-name: "*"
            update-types:
                ["version-update:semver-minor", "version-update:semver-patch"]
      schedule:
          interval: "weekly"
          day: "monday"
          time: "09:00"
      commit-message:
          prefix: "npm "
          include: scope
      groups:
          npm-dependencies:
              patterns:
                  - "*"
