version: 1
update_configs:
  - package-ecosystem: "github-actions"
    directory: "/"
    groups:
      github-action-dependencies:
        patterns:
          - "*"
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "security:patch"
  - package_manager: "python"
    directory: "/sandbox"
    update_schedule: "live"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "security:patch"
  - package_manager: "python"
    directory: "/"
    update_schedule: "live"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "security:patch"
