name: OpenAPI Validate Examples

on:
    pull_request:
        branches: [master]

permissions:
    contents: read

jobs:
    ExamplesSchemasChecks:
        name: Check ${{ matrix.endpoint.name }} Examples
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                endpoint:
                    [
                        {
                            name: "GET /Consent",
                            make_target: "schema-get-consent",
                        },
                        {
                            name: "POST /Consent",
                            make_target: "schema-post-consent",
                        },
                        {
                            name: "PATCH /Consent",
                            make_target: "schema-patch-consent",
                        },
                        {
                            name: "GET /RelatedPerson",
                            make_target: "schema-related-person",
                        },
                        {
                            name: "POST /Questionnaire",
                            make_target: "schema-questionnaire",
                        },
                        {
                            name: "GET /Questionnaire",
                            make_target: "schema-get-questionnaire",
                        },
                        { name: "Errors", make_target: "schema-errors" },
                    ]
        steps:
            - name: Checkout repository
              uses: actions/checkout@v5
              with:
                  fetch-depth: 0
                  persist-credentials: false

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: 3.9

            - name: Install Poetry
              shell: bash
              run: pipx install poetry==1.8.5

            - name: Install Script Packages with Poetry
              shell: bash
              run: poetry install --all-extras

            - name: Check Examples against Endpoint Schemas
              run: make ${{ matrix.endpoint.make_target }}
