name: Prettier Checks
on:
    pull_request:
        branches: [master]
permissions:
    contents: read
jobs:
    PrettierChecks:
        name: Prettier Checks
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
              with:
                  fetch-depth: 0
                  persist-credentials: false
            - name: Setup Node
              uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
              with:
                  node-version: 22

            - name: Install dependencies
              shell: bash
              run: npm install

            - name: Run Prettier
              shell: bash
              run: npx prettier --check .
