name: Run postman collection
on:
    workflow_dispatch:
    schedule:
        - cron: "0 0 * * *" # Runs every day at midnight UTC
jobs:
    run-postman-collection:
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repository
              uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
            - name: Set up Node.js
              uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
              with:
                  node-version: "22"
            - name: Install Newman
              run: npm install -g newman
            - name: Run Postman Collection
              run: newman run "./postman/validated_relationship_service.sandbox.postman_collection.json"
