name: SonarCloud Analysis

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "poetry"
      - name: Install Sandbox dependencies
        working-directory: sandbox
        run: poetry install
      - name: Generate Sandbox coverage report
        run: |
          VENV_PATH=$(cd sandbox && poetry env info --path)
          "$VENV_PATH/bin/pytest" --cov=sandbox/api --cov-config=sandbox/.coveragerc \
            --cov-report=xml:sandbox/coverage.xml sandbox/api/tests
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@fd88b7d7ccbaefd23d8f36f73b59db7a3d246602 # v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}